server:
  port: 9093

  
spring:
  application:
    name: api-service
  zipkin:
    base-url: http://localhost:9411

  cloud:
    gateway:
      routes:
      - id: AUTH-SERVICE
        uri: lb://AUTH-SERVICE
        predicates:
          - Path=/olx/login/**
      - id: ADVERTISE-SERVICE
        uri: lb://ADVERTISE-SERVICE
        predicates:
          - Path=/advertises/**
      - id: MASTERDATA-SERVICE
        uri: lb://MASTERDATA-SERVICE
        predicates:
          - Path=/olx/materData/**

eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    
  