server:
  port: 9092

spring:
  application:
    name: auth-service
    
  zipkin:
    base-url: http://localhost:9411
  config:
    import: configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}
    
management:
  endpoints:
    web:
      base-path: /auth-service
      exposure:
        include: '*'