server:
  port: 6767

  
spring:
   application:
     name: product-service
   datasource:
      url: jdbc:mysql://productdb-mysql-instance-1.cwp8vbjbaigr.us-east-1.rds.amazonaws.com/productdb-mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root123
   jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect