management:
  endpoints:
    web:
      base-path: /adv
      exposure:
        include: '*'
server:
  port: 9093

  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olxdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate :
        dialect: org.hibernate.dialect.MySQL8Dialect

      