management:
  endpoints:
    web:
      base-path: /advertise
      exposure:
        include: '*'
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      show-details: always
server:
  port: 9087

  
spring:
  application:
    name: advertise-service
  zipkin:
    base-url: http://localhost:9411
  config:
    import: configserver:http://localhost:8888

resilience4j:
  circuitbreaker:
    instances:
      AUTH_TOKEN_VALIDATION:
        registerHealthIndicator: true
        automaticTransitionFromOpenToHalfOpenEnabled: true
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s

eureka:
  client:
    register-with-eureka:  true
    fetch-registry: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.uuid}