spring:
 application:
  name: configuration-server
 cloud:
   config:
    server:
      git:
       uri: https://github.com/rutujapawar592/olx-app-config
       username: rutujapawar592
#       password : Rutuja@123456
       clone-on-start: true
       default-label: main

server:
  port: 8888